name: Will Runs on Developer push

on:
  push:
    branches:
      - dev/*

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Node JS
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Application Level Dependencies
        run: |
          npm i

      - name: Run Unit Tests
        run: |
          npm run build
