name: Github CI/CD Setup

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  name: build-and-test
  runs-on: self-hosted

  steps: 
    - name: checkout code
    uses: actions/checkout@v2
    - name: Install Application Level Dependencies
      run: |
        echo "Installing application level dependencies"
        npm install