name: Github CI/CD Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Node JS
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Application Level Dependencies
        run: |
          npm i

      - name: Run Unit Tests
        run: |
          npm run test

  Build:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Node Js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Application Level Dependencies
        run: |
          npm install

      - name: Build Application
        run: |
          npm run build

  Deploy:
    needs: Build

    name: Deploy to Production
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install Application Level Dependencies
        run: |
          npm i

      - name: Deploy Application
        run: |
          pm2 delete "node-js" || true
          pm2 start "npm run serve" --name "node-js"
