name: Github CI/CD Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install Application Level Dependencies
        run: |
          echo "Installing application level dependencies"
          npm install
      - name: Delete Existing process
        run: |
          pm2 delete node-js || true
      - name: start application
        run: |
          echo "Starting application"
          pm2 start "npm run serve" --name="node-js"
