name: Github CI/CD Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    name: Deploy Application
    runs-on: ubuntu-latest
    env:
      VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
      VUE_APP_STRIPE_PUBLIC_KEY: ${{ secrets.VUE_APP_STRIPE_PUBLIC_KEY }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install Application Level Dependencies
        run: |
          echo "Installing application level dependencies"
          npm install
